### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}

### Find a particular user with a givn ID
GET http://localhost:3000/auth/1
Content-Type: application/json

### Find all users with a givn email
GET http://localhost:3000/auth?email=test@test.com
Content-Type: application/json

### Remove a user given ID
DELETE http://localhost:3000/auth/1
Content-Type: application/json

### Update a user given ID
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "test1@test.com"
}